FIND_PATH(ANN_INCLUDE_DI
  NAME ANN.h ANN/ANN.h
  HINTS ${PROJECT_SOURCE_DIR}/3rdparty/ann_1.1.2/include
  )
FIND_LIBRARY(ANN_LIBRARY
  NAMES ANN libANN.so
  HINTS ${PROJECT_SOURCE_DIR}/3rdparty/ann_1.1.2/lib
  )

message(${ANN_LIBRARY})


IF (ANN_INCLUDE_DIR AND ANN_LIBRARY)
   SET(ANN_FOUND TRUE)
ELSE()
  SET(ANN_FOUND FALSE)
ENDIF()

IF (ANN_FOUND)
   IF (NOT ANN_FIND_QUIETLY)
      MESSAGE(STATUS "Found ANN: ${ANN_INCLUDE_DIR}")
   ENDIF (NOT ANN_FIND_QUIETLY)
ELSE (ANN_FOUND)
   IF (ANN_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find libANN")
   ENDIF (ANN_FIND_REQUIRED)
ENDIF (ANN_FOUND)
