FIND_PATH(ANN_INCLUDE_DIR ANN.h 
  ${PROJECT_SOURCE_DIR}/3rdparty/ann_1.1.2/include)
FIND_LIBRARY(ANN_LIBRARY NAMES ANN
  PATH ${PROJECT_SOURCE_DIR}/3rdparty/ann_1.1.2/lib) 

IF (ANN_INCLUDE_DIR)
   SET(ANN_FOUND TRUE)
ENDIF (ANN_INCLUDE_DIR)

IF (ANN_FOUND)
   IF (NOT ANN_FIND_QUIETLY)
      MESSAGE(STATUS "Found ANN: ${ANN_INCLUDE_DIR}")
   ENDIF (NOT ANN_FIND_QUIETLY)
ELSE (ANN_FOUND)
   IF (ANN_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find libANN")
   ENDIF (ANN_FIND_REQUIRED)
ENDIF (ANN_FOUND)
